name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: debug
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build-cmake:
    name: Build with CMake
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run: |
          pacman -Syu --noconfirm cmake pkg-config ninja clang mold llvm git
        shell: bash

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCOS_INSTALLER_BUILD_TESTS=ON

      - name: Build & Test
        run: |
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
          ctest --output-on-failure --test-dir ${{github.workspace}}/build/gucc/tests
        shell: bash
  build-cmake_withoutdev:
    name: Build with CMake (DEVENV OFF)
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run: |
          pacman -Syu --noconfirm cmake pkg-config ninja clang mold llvm git
        shell: bash

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_DEVENV=OFF -DCOS_INSTALLER_BUILD_TESTS=ON

      - name: Build & Test
        run: |
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
          ctest --output-on-failure --test-dir ${{github.workspace}}/build/gucc/tests
        shell: bash
